version: "3.8"

services:
  fluentd:
    build: ./
    container_name: fluentd
    image: posicube/fluentd
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PORT=${ELASTIC_PORT}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    deploy:
      mode: replicated
      resources:
        reservations:
          cpus: '1.0'
          memory: 256M
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
    networks:
      - private_net
      - public_net

networks:
  public_net:
    external: true
    name: swarm_public_net
  host_net:
    external: true
    name: host
  private_net:
    internal: true
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.32.0.0/16
