version: "3.8"

services:
  fluent-bit:
    build: ./
    container_name: fluent-bit
    image: posicube/fluent-bit
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - IGNORE_OLDER=${IGNORE_OLDER}
      - OUTPUT_HOST=${OUTPUT_HOST}
      - OUTPUT_PORT=${OUTPUT_PORT}
      - BIZ_CLIENT=${BIZ_CLIENT}
    volumes:
      - /var/log:/rootfs/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.5'
          memory: 128M
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
#     networks:
#       - private_net
#       - public_net

# networks:
#   public_net:
#     external: true
#     name: swarm_public_net
#   host_net:
#     external: true
#     name: host
#   private_net:
#     internal: true
#     driver: overlay
#     ipam:
#       driver: default
#       config:
#         - subnet: 10.32.0.0/16
